# This action ensures the "auto-merge" label can only by used
# by Nixpkgs Committers.

name: "enable auto merge"

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: read

jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write
    name: enable auto merge
    if: github.repository_owner == 'NixOS' && github.event.pull_request.merged == false && github.event.label.name == 'auto-merge'
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is committer
        id: checkAutoMergeUserIsCommitter
        uses: tspascoal/get-user-teams-membership@v3
        with:
          organization: NixOS
          team: nixpkgs-committers
          username: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # requires scope read:org

      - name: Remove label if user isn't committer
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ failure() }} | ${{ steps.checkAutoMergeUserIsCommitter.outputs.isTeamMember == 'false' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: auto-merge
